# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuHola = QtWidgets.QMenu(self.menubar)
        self.menuHola.setObjectName("menuHola")
        self.menuReserva = QtWidgets.QMenu(self.menubar)
        self.menuReserva.setObjectName("menuReserva")
        self.menuAgregar_2 = QtWidgets.QMenu(self.menubar)
        self.menuAgregar_2.setObjectName("menuAgregar_2")
        self.menuListado = QtWidgets.QMenu(self.menubar)
        self.menuListado.setObjectName("menuListado")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAgregar_Jugador = QtWidgets.QAction(MainWindow)
        self.actionAgregar_Jugador.setObjectName("actionAgregar_Jugador")
        self.actionAgregar_Cancha = QtWidgets.QAction(MainWindow)
        self.actionAgregar_Cancha.setObjectName("actionAgregar_Cancha")
        self.actionAgregar_Equipo = QtWidgets.QAction(MainWindow)
        self.actionAgregar_Equipo.setObjectName("actionAgregar_Equipo")
        self.actionRealizar_una_reserva = QtWidgets.QAction(MainWindow)
        self.actionRealizar_una_reserva.setObjectName("actionRealizar_una_reserva")
        self.actionEliminar_una_Reserva = QtWidgets.QAction(MainWindow)
        self.actionEliminar_una_Reserva.setObjectName("actionEliminar_una_Reserva")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionJugador = QtWidgets.QAction(MainWindow)
        self.actionJugador.setObjectName("actionJugador")
        self.actionCancha = QtWidgets.QAction(MainWindow)
        self.actionCancha.setObjectName("actionCancha")
        self.actionEquipo = QtWidgets.QAction(MainWindow)
        self.actionEquipo.setObjectName("actionEquipo")
        self.actionCliente = QtWidgets.QAction(MainWindow)
        self.actionCliente.setObjectName("actionCliente")
        self.actionJugadores = QtWidgets.QAction(MainWindow)
        self.actionJugadores.setObjectName("actionJugadores")
        self.actionCanchas = QtWidgets.QAction(MainWindow)
        self.actionCanchas.setObjectName("actionCanchas")
        self.actionEquipos = QtWidgets.QAction(MainWindow)
        self.actionEquipos.setObjectName("actionEquipos")
        self.actionClienres = QtWidgets.QAction(MainWindow)
        self.actionClienres.setObjectName("actionClienres")
        self.actionClientes = QtWidgets.QAction(MainWindow)
        self.actionClientes.setObjectName("actionClientes")
        self.menuHola.addAction(self.actionGuardar)
        self.menuHola.addSeparator()
        self.menuHola.addAction(self.actionSalir)
        self.menuReserva.addAction(self.actionRealizar_una_reserva)
        self.menuAgregar_2.addAction(self.actionJugador)
        self.menuAgregar_2.addAction(self.actionCancha)
        self.menuAgregar_2.addAction(self.actionEquipo)
        self.menuAgregar_2.addAction(self.actionCliente)
        self.menuListado.addAction(self.actionJugadores)
        self.menuListado.addAction(self.actionCanchas)
        self.menuListado.addAction(self.actionEquipos)
        self.menuListado.addAction(self.actionClientes)
        self.menubar.addAction(self.menuHola.menuAction())
        self.menubar.addAction(self.menuReserva.menuAction())
        self.menubar.addAction(self.menuAgregar_2.menuAction())
        self.menubar.addAction(self.menuListado.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuHola.setTitle(_translate("MainWindow", "Menu"))
        self.menuReserva.setTitle(_translate("MainWindow", "Reserva"))
        self.menuAgregar_2.setTitle(_translate("MainWindow", "Agregar"))
        self.menuListado.setTitle(_translate("MainWindow", "Listado"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAgregar_Jugador.setText(_translate("MainWindow", "Agregar Jugador"))
        self.actionAgregar_Cancha.setText(_translate("MainWindow", "Agregar Cancha"))
        self.actionAgregar_Equipo.setText(_translate("MainWindow", "Agregar Equipo"))
        self.actionRealizar_una_reserva.setText(_translate("MainWindow", "Realizar una Reserva"))
        self.actionEliminar_una_Reserva.setText(_translate("MainWindow", "Eliminar una Reserva"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionJugador.setText(_translate("MainWindow", "Jugador"))
        self.actionCancha.setText(_translate("MainWindow", "Cancha"))
        self.actionEquipo.setText(_translate("MainWindow", "Equipo"))
        self.actionCliente.setText(_translate("MainWindow", "Cliente"))
        self.actionJugadores.setText(_translate("MainWindow", "Jugadores"))
        self.actionCanchas.setText(_translate("MainWindow", "Canchas"))
        self.actionEquipos.setText(_translate("MainWindow", "Equipos"))
        self.actionClienres.setText(_translate("MainWindow", "Clientes"))
        self.actionClientes.setText(_translate("MainWindow", "Clientes"))

